# Generated by Django 4.2.1 on 2023-05-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
